// Generated by: depyler transpile ./examples/showcase/process_config.py
// Source: ./examples/showcase/process_config.py
// Command: depyler transpile ./examples/showcase/process_config.py

use std::collections::HashMap;
    #[doc = "Process configuration dictionary and return debug value if present."] #[doc = " Depyler: proven to terminate"] pub fn process_config<'a>(config: & 'a HashMap<String, String>)  -> Result<Option<String>, IndexError>{
    let mut _cse_temp_0 = config.contains_key(& "debug");
    if _cse_temp_0 {
    return Ok(config.get("debug" as usize).copied().unwrap_or_default());
   
}
return Ok(())
}