// Generated by: depyler transpile ./examples/marco_polo_cli/marco_polo_simple.py
// Source: ./examples/marco_polo_cli/marco_polo_simple.py
// Command: depyler transpile ./examples/marco_polo_cli/marco_polo_simple.py

#[doc = "Generate a number in range(simplified without random)."] #[doc = " Depyler: proven to terminate"] pub fn generate_number(min_val: i32, max_val: i32)  -> Result<i32, ZeroDivisionError>{
    let mut _cse_temp_0 = {
    let a = min_val + max_val;
    let b = 2;
    let q = a / b;
    let r = a % b;
    let r_negative = r<0;
    let b_negative = b<0;
    let needs_adjustment = r != 0 && r_negative != b_negative;
    if needs_adjustment {
    q - 1
}
else {
    q
}
};
    return Ok(_cse_temp_0);
   
}
#[doc = "Provide a hint based on the guess."] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn get_hint(guess: i32, target: i32)  -> String {
    let mut _cse_temp_0 = 50<target;
    if _cse_temp_0 {
    return "Marco!(Too low)".to_string();
   
}
else {
    let mut _cse_temp_1 = 50>target;
    if _cse_temp_1 {
    return "Marco!(Too high)".to_string();
   
}
else {
    return "Polo!".to_string();
   
}
}
}
#[doc = "Calculate final score."] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn calculate_score(attempts: i32, rounds: i32)  -> i32 {
    let mut _cse_temp_0 = rounds == 0;
    if _cse_temp_0 {
    return 0;
   
}
let mut _cse_temp_1 = 100 * rounds;
    let mut base_score = _cse_temp_1;
    let mut penalty = 0;
    let mut score = base_score - penalty;
    let mut _cse_temp_2 = score<0;
    if _cse_temp_2 {
    return 0;
   
}
return score;
   
}
#[doc = "Get difficulty name from level."] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn get_difficulty_name(level: i32)  -> & 'a str {
    let mut _cse_temp_0 = level == 1;
    if _cse_temp_0 {
    return "Easy".to_string();
   
}
else {
    let mut _cse_temp_1 = level == 2;
    if _cse_temp_1 {
    return "Medium".to_string();
   
}
else {
    let mut _cse_temp_2 = level == 3;
    if _cse_temp_2 {
    return "Hard".to_string();
   
}
else {
    return "Unknown".to_string();
   
}
}
}
} #[doc = "Calculate average with safety check."] #[doc = " Depyler: proven to terminate"] pub fn calculate_average(total: i32, count: i32)  -> Result<f64, ZeroDivisionError>{
    let mut _cse_temp_0 = count == 0;
    if _cse_temp_0 {
    return Ok(0);
   
}
let mut _cse_temp_1 = total / count;
    return Ok(_cse_temp_1);
   
}
#[doc = "Format game statistics as string."] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn format_statistics(score: i32, attempts: i32, rounds: i32)  -> String {
    let mut _inline_total = 0;
    let mut _inline_count = rounds;
    let mut _cse_temp_0 = _inline_count == 0;
    if _cse_temp_0 {
    return 0;
   
}
let mut _cse_temp_1 = _inline_total / _inline_count;
    let mut avg = _cse_temp_1;
    return "Game Statistics:\n".to_string();
   
}
#[doc = "Check if guess is in valid range."] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn validate_guess(guess: i32, min_val: i32, max_val: i32)  -> bool {
    let mut _cse_temp_0 = 50<min_val;
    if _cse_temp_0 {
    return false;
   
}
let mut _cse_temp_1 = 50>max_val;
    if _cse_temp_1 {
    return false;
   
}
return true;
   
}
#[doc = "Simulate a round with fixed guesses."] #[doc = " Depyler: verified panic-free"] pub fn play_simple_round(target: i32, max_attempts: i32)  -> i32 {
    while 0<max_attempts {
    let mut attempts = 1;
    if 50 == target {
    return 0;
   
}
else {
    if 50<target {
    let mut guess = 60;
   
}
else {
    let mut guess = 45;
   
}
}
}
return 0;
   
}
#[cfg(test)] mod tests {
    use super::*;
    use quickcheck::{
    quickcheck, TestResult };
    #[test] fn test_generate_number_examples() {
    assert_eq !(generate_number(0, 0), 0);
    assert_eq !(generate_number(1, 2), 3);
    assert_eq !(generate_number(- 1, 1), 0);
   
}
} #[cfg(test)] mod tests {
    use super::*;
    use quickcheck::{
    quickcheck, TestResult };
    #[test] fn test_calculate_score_examples() {
    assert_eq !(calculate_score(0, 0), 0);
    assert_eq !(calculate_score(1, 2), 3);
    assert_eq !(calculate_score(- 1, 1), 0);
   
}
} #[cfg(test)] mod tests {
    use super::*;
    use quickcheck::{
    quickcheck, TestResult };
    #[test] fn test_play_simple_round_examples() {
    assert_eq !(play_simple_round(0, 0), 0);
    assert_eq !(play_simple_round(1, 2), 3);
    assert_eq !(play_simple_round(- 1, 1), 0);
   
}
}