# Depyler Mutation Testing Configuration
# Spec: docs/specifications/mutant.md
# Target: ≥90% mutation kill rate

# Timeout multiplier (default baseline test time * 5)
timeout_multiplier = 5.0

# Minimum timeout per mutant (2 minutes)
minimum_test_timeout = 120

# Exclude patterns
exclude_globs = [
    "**/tests/**",           # Don't mutate test code
    "**/*_test.rs",          # Don't mutate test helpers
    "**/examples/**",        # Don't mutate examples
]

# Test only depyler-core package (not whole workspace)
# This avoids timeout issues with ruchy integration tests
test_package = ["depyler-core"]

# Additional test arguments
# Note: --release removed due to disk space constraints (builds are ~5x larger)
# Note: cargo-mutants runs tests in a tmp directory where doctests fail
# But unit tests (342) and integration tests all pass, which is what matters for mutation testing
additional_cargo_test_args = ["--lib", "--tests"]

# WORKAROUND: Baseline skip for doctest issues
# When running mutation tests manually, use --baseline skip flag:
#   cargo mutants --baseline skip --file <file> --jobs 2
# This bypasses baseline validation (safe because we validate tests pass separately)
# We verify all 596 tests pass via: cargo test -p depyler-core --lib --tests
