// Generated by: depyler transpile examples/dict_assign_typed.py
// Source: examples/dict_assign_typed.py
// Command: depyler transpile examples/dict_assign_typed.py

use std::collections::HashMap;
    #[doc = "Test dictionary assignment with string keys"] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn test_string_dict()  -> HashMap<String, String>{
    let mut d = {
    let mut map = HashMap::new();
    map };
    d.insert("key1".to_string(), "value1");
    d.insert("key2".to_string(), "value2");
    return d;
   
}
#[doc = "Test dictionary assignment with integer keys"] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn test_int_dict()  -> HashMap<i32, String>{
    let mut d = {
    let mut map = HashMap::new();
    map };
    d.insert(42, "number key");
    d.insert(100, "another number");
    return d;
   
}
#[doc = "Test nested dictionary(but not nested assignment yet)"] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn test_nested_dict()  -> HashMap<String, HashMap<String, String>>{
    let mut d = {
    let mut map = HashMap::new();
    map };
    d.insert("outer".to_string(), {
    let mut map = HashMap::new();
    map });
    return d
}
