# Generated by: depyler corpus generator
# Source: hard_cp_ds_persistent.py
#
# Persistent array (copy-on-write simulation) for transpiler stress testing.


def persistent_create(size: int, default_val: int) -> list[int]:
    """Create a persistent array of given size with default value."""
    arr: list[int] = [default_val] * size
    return arr


def persistent_set(arr: list[int], idx: int, val: int) -> list[int]:
    """Set value at index, return new version (copy-on-write)."""
    new_arr: list[int] = []
    i: int = 0
    while i < len(arr):
        if i == idx:
            new_arr.append(val)
        else:
            new_arr.append(arr[i])
        i = i + 1
    return new_arr


def persistent_get(arr: list[int], idx: int) -> int:
    """Get value at index."""
    if idx < 0 or idx >= len(arr):
        return 0 - 1
    return arr[idx]


def persistent_push(arr: list[int], val: int) -> list[int]:
    """Append value, return new version."""
    new_arr: list[int] = []
    i: int = 0
    while i < len(arr):
        new_arr.append(arr[i])
        i = i + 1
    new_arr.append(val)
    return new_arr


def persistent_pop(arr: list[int]) -> list[int]:
    """Remove last element, return new version."""
    new_arr: list[int] = []
    i: int = 0
    while i < len(arr) - 1:
        new_arr.append(arr[i])
        i = i + 1
    return new_arr


def version_history_sum(versions: list[list[int]], ver: int) -> int:
    """Sum all elements in a given version."""
    arr: list[int] = versions[ver]
    total: int = 0
    i: int = 0
    while i < len(arr):
        total = total + arr[i]
        i = i + 1
    return total


def test_module() -> int:
    passed: int = 0
    v0: list[int] = persistent_create(5, 0)
    v1: list[int] = persistent_set(v0, 2, 10)
    if persistent_get(v0, 2) == 0:
        passed = passed + 1
    if persistent_get(v1, 2) == 10:
        passed = passed + 1
    v2: list[int] = persistent_push(v1, 20)
    if len(v2) == 6:
        passed = passed + 1
    v3: list[int] = persistent_pop(v2)
    if len(v3) == 5:
        passed = passed + 1
    versions: list[list[int]] = [v0, v1, v2]
    if version_history_sum(versions, 1) == 10:
        passed = passed + 1
    return passed
