# Generated by: depyler corpus generator
# Source: hard_cp_string_kmp.py
#
# KMP string matching for transpiler stress testing.


def kmp_build_failure(pat: str) -> list[int]:
    """Build KMP failure/prefix function."""
    m: int = len(pat)
    if m == 0:
        return []
    fail: list[int] = [0] * m
    k: int = 0
    j: int = 1
    while j < m:
        while k > 0 and pat[k] != pat[j]:
            k = fail[k - 1]
        if pat[k] == pat[j]:
            k = k + 1
        fail[j] = k
        j = j + 1
    return fail


def kmp_search_count(text: str, pat: str) -> int:
    """Count occurrences of pattern in text using KMP."""
    n: int = len(text)
    m: int = len(pat)
    if m == 0 or m > n:
        return 0
    fail: list[int] = kmp_build_failure(pat)
    count: int = 0
    j: int = 0
    i: int = 0
    while i < n:
        while j > 0 and pat[j] != text[i]:
            j = fail[j - 1]
        if pat[j] == text[i]:
            j = j + 1
        if j == m:
            count = count + 1
            j = fail[j - 1]
        i = i + 1
    return count


def kmp_first_occurrence(text: str, pat: str) -> int:
    """Find first occurrence of pattern in text. Returns -1 if not found."""
    n: int = len(text)
    m: int = len(pat)
    if m == 0 or m > n:
        return 0 - 1
    fail: list[int] = kmp_build_failure(pat)
    j: int = 0
    i: int = 0
    while i < n:
        while j > 0 and pat[j] != text[i]:
            j = fail[j - 1]
        if pat[j] == text[i]:
            j = j + 1
        if j == m:
            return i - m + 1
        i = i + 1
    return 0 - 1


def kmp_all_positions(text: str, pat: str) -> list[int]:
    """Find all start positions of pattern in text."""
    n: int = len(text)
    m: int = len(pat)
    result: list[int] = []
    if m == 0 or m > n:
        return result
    fail: list[int] = kmp_build_failure(pat)
    j: int = 0
    i: int = 0
    while i < n:
        while j > 0 and pat[j] != text[i]:
            j = fail[j - 1]
        if pat[j] == text[i]:
            j = j + 1
        if j == m:
            result.append(i - m + 1)
            j = fail[j - 1]
        i = i + 1
    return result


def test_module() -> int:
    passed: int = 0
    if kmp_search_count("ababababab", "abab") == 4:
        passed = passed + 1
    if kmp_first_occurrence("hello world", "world") == 6:
        passed = passed + 1
    if kmp_first_occurrence("abc", "xyz") == 0 - 1:
        passed = passed + 1
    positions: list[int] = kmp_all_positions("aaaaaa", "aa")
    if len(positions) == 5:
        passed = passed + 1
    fail: list[int] = kmp_build_failure("abcabd")
    if fail[5] == 0:
        passed = passed + 1
    return passed
