# Generated by: depyler corpus generator
# Source: hard_adv_net_routing.py
#
# Routing table operations: lookup, longest prefix match, route aggregation.


def prefix_match_length(addr: int, route_addr: int, mask_bits: int) -> int:
    """Check how many high bits of addr match route_addr under mask."""
    shift: int = 32 - mask_bits
    a_masked: int = addr >> shift
    r_masked: int = route_addr >> shift
    if a_masked == r_masked:
        return mask_bits
    return 0


def lookup_route(addr: int, routes_addr: list[int], routes_mask: list[int], routes_nexthop: list[int]) -> int:
    """Find best matching route (longest prefix match). Returns next-hop or -1."""
    best_match: int = -1
    best_len: int = 0
    i: int = 0
    n: int = len(routes_addr)
    while i < n:
        ra: int = routes_addr[i]
        rm: int = routes_mask[i]
        match_len: int = prefix_match_length(addr, ra, rm)
        if match_len > best_len:
            best_len = match_len
            best_match = i
        i = i + 1
    if best_match >= 0:
        return routes_nexthop[best_match]
    return -1


def add_route(routes_addr: list[int], routes_mask: list[int], routes_nexthop: list[int],
              new_addr: int, new_mask: int, new_hop: int) -> int:
    """Add a route to the table. Returns new table size."""
    routes_addr.append(new_addr)
    routes_mask.append(new_mask)
    routes_nexthop.append(new_hop)
    return len(routes_addr)


def remove_route(routes_addr: list[int], routes_mask: list[int], routes_nexthop: list[int],
                 idx: int) -> int:
    """Remove route at index by replacing with last entry. Returns new size."""
    n: int = len(routes_addr)
    if idx < 0 or idx >= n:
        return n
    last: int = n - 1
    if idx != last:
        routes_addr[idx] = routes_addr[last]
        routes_mask[idx] = routes_mask[last]
        routes_nexthop[idx] = routes_nexthop[last]
    routes_addr.pop()
    routes_mask.pop()
    routes_nexthop.pop()
    return n - 1


def count_routes_by_mask(routes_mask: list[int], target_mask: int) -> int:
    """Count routes with a specific mask length."""
    cnt: int = 0
    i: int = 0
    n: int = len(routes_mask)
    while i < n:
        mv: int = routes_mask[i]
        if mv == target_mask:
            cnt = cnt + 1
        i = i + 1
    return cnt


def test_module() -> int:
    """Test routing table functions."""
    passed: int = 0

    pm: int = prefix_match_length(3232235520, 3232235520, 24)
    if pm == 24:
        passed = passed + 1

    pm2: int = prefix_match_length(167772160, 3232235520, 24)
    if pm2 == 0:
        passed = passed + 1

    ra: list[int] = [3232235520, 167772160]
    rm: list[int] = [24, 8]
    rn: list[int] = [1, 2]
    hop: int = lookup_route(167772161, ra, rm, rn)
    if hop == 2:
        passed = passed + 1

    sz: int = add_route(ra, rm, rn, 2886729728, 16, 3)
    if sz == 3:
        passed = passed + 1

    cnt: int = count_routes_by_mask(rm, 24)
    if cnt == 1:
        passed = passed + 1

    sz2: int = remove_route(ra, rm, rn, 0)
    if sz2 == 2:
        passed = passed + 1

    return passed
