# Generated by: depyler corpus generator
# Source: hard_adv_comp_rle.py
#
# Run-length encoding and decoding for integer sequences.


def rle_encode(data: list[int]) -> list[int]:
    """RLE encode: output pairs [value, count, value, count, ...]."""
    result: list[int] = []
    n: int = len(data)
    if n == 0:
        return result
    i: int = 0
    while i < n:
        current: int = data[i]
        run_len: int = 1
        while i + run_len < n:
            next_val: int = data[i + run_len]
            if next_val != current:
                break
            run_len = run_len + 1
        result.append(current)
        result.append(run_len)
        i = i + run_len
    return result


def rle_decode(encoded: list[int]) -> list[int]:
    """Decode RLE data back to original sequence."""
    result: list[int] = []
    i: int = 0
    n: int = len(encoded)
    while i < n - 1:
        val: int = encoded[i]
        cnt: int = encoded[i + 1]
        j: int = 0
        while j < cnt:
            result.append(val)
            j = j + 1
        i = i + 2
    return result


def rle_size(encoded: list[int]) -> int:
    """Get the number of runs in RLE data."""
    return len(encoded) // 2


def compression_ratio(original_len: int, encoded_len: int) -> int:
    """Compute compression ratio as percentage (100 = no compression)."""
    if original_len == 0:
        return 100
    return (encoded_len * 100) // original_len


def rle_merge(enc_a: list[int], enc_b: list[int]) -> list[int]:
    """Merge two RLE streams, combining adjacent same-value runs."""
    merged: list[int] = []
    i: int = 0
    na: int = len(enc_a)
    while i < na:
        val: int = enc_a[i]
        cnt: int = enc_a[i + 1]
        merged.append(val)
        merged.append(cnt)
        i = i + 2
    j: int = 0
    nb: int = len(enc_b)
    while j < nb:
        val2: int = enc_b[j]
        cnt2: int = enc_b[j + 1]
        m_len: int = len(merged)
        if m_len >= 2:
            last_val: int = merged[m_len - 2]
            if last_val == val2:
                old_cnt: int = merged[m_len - 1]
                merged[m_len - 1] = old_cnt + cnt2
            else:
                merged.append(val2)
                merged.append(cnt2)
        else:
            merged.append(val2)
            merged.append(cnt2)
        j = j + 2
    return merged


def test_module() -> int:
    """Test RLE functions."""
    passed: int = 0

    enc: list[int] = rle_encode([1, 1, 1, 2, 2, 3])
    if len(enc) == 6:
        passed = passed + 1

    dec: list[int] = rle_decode(enc)
    if len(dec) == 6:
        passed = passed + 1

    runs: int = rle_size(enc)
    if runs == 3:
        passed = passed + 1

    cr: int = compression_ratio(6, 6)
    if cr == 100:
        passed = passed + 1

    enc2: list[int] = rle_encode([5, 5, 5, 5, 5])
    cr2: int = compression_ratio(5, len(enc2))
    if cr2 < 100:
        passed = passed + 1

    m: list[int] = rle_merge([1, 3], [1, 2])
    if len(m) == 2:
        passed = passed + 1

    return passed
