# Generated by: depyler corpus generator
# Source: hard_cp_math_discretelog.py
#
# Discrete logarithm (baby-step giant-step) for transpiler stress testing.


def mod_pow(base_val: int, exp: int, mod: int) -> int:
    """Modular exponentiation."""
    result: int = 1
    b: int = base_val % mod
    e: int = exp
    while e > 0:
        if e % 2 == 1:
            result = (result * b) % mod
        e = e // 2
        b = (b * b) % mod
    return result


def isqrt(n: int) -> int:
    """Integer square root."""
    if n < 0:
        return 0
    if n == 0:
        return 0
    x: int = n
    y: int = (x + 1) // 2
    while y < x:
        x = y
        y = (x + n // x) // 2
    return x


def baby_giant_step(g: int, h: int, p: int) -> int:
    """Solve g^x = h (mod p) for x. Returns -1 if no solution."""
    m: int = isqrt(p) + 1
    table_vals: list[int] = []
    table_keys: list[int] = []
    power: int = 1
    j: int = 0
    while j < m:
        table_vals.append(power)
        table_keys.append(j)
        power = (power * g) % p
        j = j + 1
    gm_inv: int = mod_pow(g, p - 1 - m, p)
    gamma: int = h
    i: int = 0
    while i < m:
        k: int = 0
        while k < len(table_vals):
            if table_vals[k] == gamma:
                return i * m + table_keys[k]
            k = k + 1
        gamma = (gamma * gm_inv) % p
        i = i + 1
    return 0 - 1


def order_of_element(g: int, p: int) -> int:
    """Find multiplicative order of g modulo p."""
    if g % p == 0:
        return 0
    power: int = g % p
    ord_val: int = 1
    while power != 1:
        power = (power * g) % p
        ord_val = ord_val + 1
        if ord_val > p:
            return 0 - 1
    return ord_val


def test_module() -> int:
    passed: int = 0
    if mod_pow(2, 10, 1000) == 24:
        passed = passed + 1
    if isqrt(16) == 4:
        passed = passed + 1
    if isqrt(15) == 3:
        passed = passed + 1
    x: int = baby_giant_step(2, 8, 13)
    if mod_pow(2, x, 13) == 8:
        passed = passed + 1
    if order_of_element(2, 7) == 3:
        passed = passed + 1
    return passed
