# Generated by: depyler corpus generator
# Source: hard_algo_counting_sort.py
#
# Counting sort and radix sort concepts for non-negative integers.


def counting_sort(arr: List[int], max_val: int) -> List[int]:
    """Counting sort for non-negative integers up to max_val."""
    n: int = len(arr)
    if n == 0:
        return []
    counts: List[int] = []
    i: int = 0
    while i <= max_val:
        counts.append(0)
        i = i + 1
    j: int = 0
    while j < n:
        idx: int = arr[j]
        counts[idx] = counts[idx] + 1
        j = j + 1
    result: List[int] = []
    v: int = 0
    while v <= max_val:
        c: int = 0
        while c < counts[v]:
            result.append(v)
            c = c + 1
        v = v + 1
    return result


def counting_sort_stable(arr: List[int], max_val: int) -> List[int]:
    """Stable counting sort preserving relative order."""
    n: int = len(arr)
    if n == 0:
        return []
    counts: List[int] = []
    i: int = 0
    while i <= max_val:
        counts.append(0)
        i = i + 1
    j: int = 0
    while j < n:
        idx: int = arr[j]
        counts[idx] = counts[idx] + 1
        j = j + 1
    k: int = 1
    while k <= max_val:
        counts[k] = counts[k] + counts[k - 1]
        k = k + 1
    output: List[int] = [0] * n
    m: int = n - 1
    while m >= 0:
        val: int = arr[m]
        counts[val] = counts[val] - 1
        pos: int = counts[val]
        output[pos] = val
        m = m - 1
    return output


def get_digit(num: int, exp: int) -> int:
    """Extract digit at given place value."""
    return (num // exp) % 10


def radix_sort_lsd(arr: List[int]) -> List[int]:
    """LSD radix sort for non-negative integers."""
    n: int = len(arr)
    if n == 0:
        return []
    max_val: int = arr[0]
    i: int = 1
    while i < n:
        if arr[i] > max_val:
            max_val = arr[i]
        i = i + 1
    result: List[int] = []
    i = 0
    while i < n:
        result.append(arr[i])
        i = i + 1
    exp: int = 1
    while max_val // exp > 0:
        buckets: List[int] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        j: int = 0
        while j < n:
            d: int = get_digit(result[j], exp)
            buckets[d] = buckets[d] + 1
            j = j + 1
        k: int = 1
        while k < 10:
            buckets[k] = buckets[k] + buckets[k - 1]
            k = k + 1
        output: List[int] = [0] * n
        m: int = n - 1
        while m >= 0:
            d2: int = get_digit(result[m], exp)
            buckets[d2] = buckets[d2] - 1
            pos: int = buckets[d2]
            output[pos] = result[m]
            m = m - 1
        result = output
        exp = exp * 10
    return result


def frequency_sort(arr: List[int], max_val: int) -> List[int]:
    """Sort by frequency (least frequent first), break ties by value."""
    n: int = len(arr)
    if n == 0:
        return []
    counts: List[int] = []
    i: int = 0
    while i <= max_val:
        counts.append(0)
        i = i + 1
    j: int = 0
    while j < n:
        counts[arr[j]] = counts[arr[j]] + 1
        j = j + 1
    result: List[int] = []
    i = 0
    while i < n:
        result.append(arr[i])
        i = i + 1
    i = 0
    while i < n - 1:
        j = i + 1
        while j < n:
            ci: int = counts[result[i]]
            cj: int = counts[result[j]]
            swap: int = 0
            if ci > cj:
                swap = 1
            elif ci == cj and result[i] > result[j]:
                swap = 1
            if swap == 1:
                tmp: int = result[i]
                result[i] = result[j]
                result[j] = tmp
            j = j + 1
        i = i + 1
    return result


def test_module() -> int:
    """Test all counting sort and radix functions."""
    passed: int = 0

    r1: List[int] = counting_sort([4, 2, 2, 8, 3, 3, 1], 9)
    if r1 == [1, 2, 2, 3, 3, 4, 8]:
        passed = passed + 1

    r2: List[int] = counting_sort([], 5)
    if r2 == []:
        passed = passed + 1

    r3: List[int] = counting_sort_stable([4, 2, 2, 8, 3], 9)
    if r3 == [2, 2, 3, 4, 8]:
        passed = passed + 1

    r4: List[int] = radix_sort_lsd([170, 45, 75, 90, 802, 24, 2, 66])
    if r4 == [2, 24, 45, 66, 75, 90, 170, 802]:
        passed = passed + 1

    r5: List[int] = radix_sort_lsd([])
    if r5 == []:
        passed = passed + 1

    r6: int = get_digit(12345, 100)
    if r6 == 3:
        passed = passed + 1

    r7: List[int] = radix_sort_lsd([999, 1, 100, 10])
    if r7 == [1, 10, 100, 999]:
        passed = passed + 1

    return passed
