# Generated by: depyler corpus generator
# Source: hard_cp_string_anagram.py
#
# Anagram grouping and detection for transpiler stress testing.


def are_anagrams(s1: str, s2: str) -> int:
    """Check if two strings are anagrams. Returns 1=yes, 0=no."""
    if len(s1) != len(s2):
        return 0
    freq: list[int] = [0] * 256
    i: int = 0
    while i < len(s1):
        idx1: int = ord(s1[i])
        freq[idx1] = freq[idx1] + 1
        i = i + 1
    j: int = 0
    while j < len(s2):
        idx2: int = ord(s2[j])
        freq[idx2] = freq[idx2] - 1
        j = j + 1
    k: int = 0
    while k < 256:
        if freq[k] != 0:
            return 0
        k = k + 1
    return 1


def count_anagram_pairs(words: list[str]) -> int:
    """Count pairs of words that are anagrams of each other."""
    n: int = len(words)
    count: int = 0
    i: int = 0
    while i < n:
        j: int = i + 1
        while j < n:
            if are_anagrams(words[i], words[j]) == 1:
                count = count + 1
            j = j + 1
        i = i + 1
    return count


def min_deletions_anagram(s1: str, s2: str) -> int:
    """Min deletions to make two strings anagrams of each other."""
    freq1: list[int] = [0] * 256
    freq2: list[int] = [0] * 256
    i: int = 0
    while i < len(s1):
        idx: int = ord(s1[i])
        freq1[idx] = freq1[idx] + 1
        i = i + 1
    j: int = 0
    while j < len(s2):
        idx2: int = ord(s2[j])
        freq2[idx2] = freq2[idx2] + 1
        j = j + 1
    deletions: int = 0
    k: int = 0
    while k < 256:
        diff: int = freq1[k] - freq2[k]
        if diff < 0:
            diff = 0 - diff
        deletions = deletions + diff
        k = k + 1
    return deletions


def group_anagram_count(words: list[str]) -> int:
    """Count number of anagram groups."""
    n: int = len(words)
    if n == 0:
        return 0
    assigned: list[int] = [0] * n
    groups: int = 0
    i: int = 0
    while i < n:
        if assigned[i] == 0:
            assigned[i] = 1
            groups = groups + 1
            j: int = i + 1
            while j < n:
                if assigned[j] == 0 and are_anagrams(words[i], words[j]) == 1:
                    assigned[j] = 1
                j = j + 1
        i = i + 1
    return groups


def test_module() -> int:
    passed: int = 0
    if are_anagrams("listen", "silent") == 1:
        passed = passed + 1
    if are_anagrams("hello", "world") == 0:
        passed = passed + 1
    if count_anagram_pairs(["abc", "bca", "cab", "xyz"]) == 3:
        passed = passed + 1
    if min_deletions_anagram("abc", "bcd") == 2:
        passed = passed + 1
    if group_anagram_count(["eat", "tea", "tan", "ate", "nat", "bat"]) == 3:
        passed = passed + 1
    return passed
