# Generated by: depyler corpus generator
# Source: hard_cp_string_palindrome.py
#
# Longest palindromic subsequence and related for transpiler stress testing.


def longest_palindromic_subseq(s: str) -> int:
    """Length of longest palindromic subsequence using 2D DP."""
    n: int = len(s)
    if n == 0:
        return 0
    dp: list[list[int]] = []
    r: int = 0
    while r < n:
        row: list[int] = [0] * n
        dp.append(row)
        r = r + 1
    i: int = 0
    while i < n:
        dp[i][i] = 1
        i = i + 1
    length: int = 2
    while length <= n:
        start: int = 0
        while start <= n - length:
            end: int = start + length - 1
            if s[start] == s[end]:
                if length == 2:
                    dp[start][end] = 2
                else:
                    dp[start][end] = dp[start + 1][end - 1] + 2
            else:
                left: int = dp[start + 1][end]
                right: int = dp[start][end - 1]
                if left > right:
                    dp[start][end] = left
                else:
                    dp[start][end] = right
            start = start + 1
        length = length + 1
    return dp[0][n - 1]


def is_palindrome(s: str) -> int:
    """Check if string is palindrome. Returns 1=yes, 0=no."""
    n: int = len(s)
    left: int = 0
    right: int = n - 1
    while left < right:
        if s[left] != s[right]:
            return 0
        left = left + 1
        right = right - 1
    return 1


def count_palindromic_substrings(s: str) -> int:
    """Count number of palindromic substrings using expand around center."""
    n: int = len(s)
    count: int = 0
    center: int = 0
    while center < 2 * n - 1:
        left: int = center // 2
        right: int = center // 2 + center % 2
        while left >= 0 and right < n and s[left] == s[right]:
            count = count + 1
            left = left - 1
            right = right + 1
        center = center + 1
    return count


def longest_palindrome_length(s: str) -> int:
    """Length of longest palindromic substring."""
    n: int = len(s)
    best: int = 0
    center: int = 0
    while center < 2 * n - 1:
        left: int = center // 2
        right: int = center // 2 + center % 2
        while left >= 0 and right < n and s[left] == s[right]:
            curr_len: int = right - left + 1
            if curr_len > best:
                best = curr_len
            left = left - 1
            right = right + 1
        center = center + 1
    return best


def min_insertions_palindrome(s: str) -> int:
    """Minimum insertions to make string palindrome = n - LPS."""
    n: int = len(s)
    lps: int = longest_palindromic_subseq(s)
    return n - lps


def test_module() -> int:
    passed: int = 0
    if longest_palindromic_subseq("bbbab") == 4:
        passed = passed + 1
    if is_palindrome("racecar") == 1:
        passed = passed + 1
    if is_palindrome("hello") == 0:
        passed = passed + 1
    if count_palindromic_substrings("aaa") == 6:
        passed = passed + 1
    if longest_palindrome_length("babad") == 3:
        passed = passed + 1
    if min_insertions_palindrome("abc") == 2:
        passed = passed + 1
    return passed
