# Generated by: depyler corpus generator
# Source: hard_algo_two_pointer.py
#
# Two pointer technique patterns.


def two_sum_sorted(arr: List[int], target: int) -> List[int]:
    """Find two indices in sorted array whose elements sum to target."""
    lo: int = 0
    hi: int = len(arr) - 1
    while lo < hi:
        s: int = arr[lo] + arr[hi]
        if s == target:
            return [lo, hi]
        elif s < target:
            lo = lo + 1
        else:
            hi = hi - 1
    return [-1, -1]


def remove_duplicates_sorted(arr: List[int]) -> List[int]:
    """Remove duplicates from sorted array, return new array."""
    n: int = len(arr)
    if n == 0:
        return []
    result: List[int] = [arr[0]]
    i: int = 1
    while i < n:
        if arr[i] != arr[i - 1]:
            result.append(arr[i])
        i = i + 1
    return result


def container_water(heights: List[int]) -> int:
    """Container with most water (two pointer)."""
    n: int = len(heights)
    if n < 2:
        return 0
    lo: int = 0
    hi: int = n - 1
    best: int = 0
    while lo < hi:
        h: int = heights[lo]
        if heights[hi] < h:
            h = heights[hi]
        area: int = h * (hi - lo)
        if area > best:
            best = area
        if heights[lo] < heights[hi]:
            lo = lo + 1
        else:
            hi = hi - 1
    return best


def move_zeroes(arr: List[int]) -> List[int]:
    """Move all zeroes to end of array, preserving order of non-zeroes."""
    result: List[int] = []
    i: int = 0
    while i < len(arr):
        result.append(arr[i])
        i = i + 1
    n: int = len(result)
    write_pos: int = 0
    read_pos: int = 0
    while read_pos < n:
        if result[read_pos] != 0:
            result[write_pos] = result[read_pos]
            write_pos = write_pos + 1
        read_pos = read_pos + 1
    while write_pos < n:
        result[write_pos] = 0
        write_pos = write_pos + 1
    return result


def reverse_array(arr: List[int]) -> List[int]:
    """Reverse an array using two pointers."""
    result: List[int] = []
    i: int = 0
    while i < len(arr):
        result.append(arr[i])
        i = i + 1
    lo: int = 0
    hi: int = len(result) - 1
    while lo < hi:
        tmp: int = result[lo]
        result[lo] = result[hi]
        result[hi] = tmp
        lo = lo + 1
        hi = hi - 1
    return result


def is_palindrome_array(arr: List[int]) -> int:
    """Check if array is palindrome. Returns 1 if yes, 0 if no."""
    n: int = len(arr)
    lo: int = 0
    hi: int = n - 1
    while lo < hi:
        if arr[lo] != arr[hi]:
            return 0
        lo = lo + 1
        hi = hi - 1
    return 1


def test_module() -> int:
    """Test all two pointer functions."""
    passed: int = 0

    r1: List[int] = two_sum_sorted([2, 7, 11, 15], 9)
    if r1 == [0, 1]:
        passed = passed + 1

    r2: List[int] = two_sum_sorted([1, 2, 3], 10)
    if r2 == [-1, -1]:
        passed = passed + 1

    r3: List[int] = remove_duplicates_sorted([1, 1, 2, 2, 3, 4, 4])
    if r3 == [1, 2, 3, 4]:
        passed = passed + 1

    r4: int = container_water([1, 8, 6, 2, 5, 4, 8, 3, 7])
    if r4 == 49:
        passed = passed + 1

    r5: List[int] = move_zeroes([0, 1, 0, 3, 12])
    if r5 == [1, 3, 12, 0, 0]:
        passed = passed + 1

    r6: List[int] = reverse_array([1, 2, 3, 4, 5])
    if r6 == [5, 4, 3, 2, 1]:
        passed = passed + 1

    r7: int = is_palindrome_array([1, 2, 3, 2, 1])
    if r7 == 1:
        passed = passed + 1

    r8: int = is_palindrome_array([1, 2, 3])
    if r8 == 0:
        passed = passed + 1

    return passed
