# Generated by: depyler corpus generator
# Source: hard_adv_comp_delta.py
#
# Delta encoding and decoding for time-series integer data.


def delta_encode(data: list[int]) -> list[int]:
    """Delta encode: store first value, then differences."""
    n: int = len(data)
    if n == 0:
        return []
    result: list[int] = []
    first: int = data[0]
    result.append(first)
    i: int = 1
    while i < n:
        prev: int = data[i - 1]
        cur: int = data[i]
        diff: int = cur - prev
        result.append(diff)
        i = i + 1
    return result


def delta_decode(encoded: list[int]) -> list[int]:
    """Decode delta-encoded data back to original."""
    n: int = len(encoded)
    if n == 0:
        return []
    result: list[int] = []
    first: int = encoded[0]
    result.append(first)
    i: int = 1
    while i < n:
        delta: int = encoded[i]
        prev: int = result[i - 1]
        result.append(prev + delta)
        i = i + 1
    return result


def double_delta_encode(data: list[int]) -> list[int]:
    """Apply delta encoding twice for quadratic trends."""
    first_pass: list[int] = delta_encode(data)
    return delta_encode(first_pass)


def double_delta_decode(encoded: list[int]) -> list[int]:
    """Decode double-delta encoded data."""
    first_pass: list[int] = delta_decode(encoded)
    return delta_decode(first_pass)


def delta_range(encoded: list[int]) -> int:
    """Compute the range (max - min) of delta values (excluding first element)."""
    n: int = len(encoded)
    if n <= 1:
        return 0
    min_d: int = encoded[1]
    max_d: int = encoded[1]
    i: int = 2
    while i < n:
        dv: int = encoded[i]
        if dv < min_d:
            min_d = dv
        if dv > max_d:
            max_d = dv
        i = i + 1
    return max_d - min_d


def zigzag_encode_val(val: int) -> int:
    """Zigzag encode a signed integer to unsigned."""
    if val >= 0:
        return val * 2
    return (0 - val) * 2 - 1


def zigzag_decode_val(val: int) -> int:
    """Zigzag decode an unsigned integer to signed."""
    if val % 2 == 0:
        return val // 2
    return 0 - (val + 1) // 2


def test_module() -> int:
    """Test delta encoding functions."""
    passed: int = 0

    enc: list[int] = delta_encode([10, 12, 15, 20])
    e0: int = enc[0]
    e1: int = enc[1]
    if e0 == 10 and e1 == 2:
        passed = passed + 1

    dec: list[int] = delta_decode(enc)
    d0: int = dec[0]
    d3: int = dec[3]
    if d0 == 10 and d3 == 20:
        passed = passed + 1

    dd_enc: list[int] = double_delta_encode([1, 3, 6, 10])
    dd_dec: list[int] = double_delta_decode(dd_enc)
    dd0: int = dd_dec[0]
    dd3: int = dd_dec[3]
    if dd0 == 1 and dd3 == 10:
        passed = passed + 1

    rng: int = delta_range([100, 1, 1, 1])
    if rng == 0:
        passed = passed + 1

    zz1: int = zigzag_encode_val(0 - 3)
    if zz1 == 5:
        passed = passed + 1

    zz2: int = zigzag_decode_val(5)
    if zz2 == 0 - 3:
        passed = passed + 1

    return passed
