# Generated by: depyler corpus generator
# Source: hard_adv_parse_expr.py
#
# Expression evaluator for simple arithmetic on integer tokens.
# Tokens: numbers (>=0), operators (+ = 43, - = 45, * = 42), parens (40, 41).
# Uses -1 sentinel for end.


def is_digit_token(tok: int) -> int:
    """Check if token represents a digit (0-9 encoded as 48-57)."""
    if tok >= 48 and tok <= 57:
        return 1
    return 0


def token_to_digit(tok: int) -> int:
    """Convert ASCII digit token to integer value."""
    return tok - 48


def parse_number(tokens: list[int], pos: int) -> tuple[int, int]:
    """Parse a multi-digit number starting at pos. Returns (value, new_pos)."""
    num: int = 0
    cur: int = pos
    n: int = len(tokens)
    while cur < n:
        tok: int = tokens[cur]
        is_d: int = is_digit_token(tok)
        if is_d == 0:
            return (num, cur)
        num = num * 10 + token_to_digit(tok)
        cur = cur + 1
    return (num, cur)


def eval_simple(tokens: list[int]) -> int:
    """Evaluate a flat expression with + and - only (no parens, no precedence)."""
    n: int = len(tokens)
    if n == 0:
        return 0
    pair: tuple[int, int] = parse_number(tokens, 0)
    result: int = pair[0]
    pos: int = pair[1]
    while pos < n:
        op: int = tokens[pos]
        pos = pos + 1
        pair2: tuple[int, int] = parse_number(tokens, pos)
        operand: int = pair2[0]
        pos = pair2[1]
        if op == 43:
            result = result + operand
        elif op == 45:
            result = result - operand
        elif op == 42:
            result = result * operand
    return result


def tokenize_digits(value: int) -> list[int]:
    """Convert an integer to list of ASCII digit tokens."""
    if value == 0:
        return [48]
    digits: list[int] = []
    v: int = value
    while v > 0:
        d: int = v % 10
        digits.append(d + 48)
        v = v // 10
    result: list[int] = []
    i: int = len(digits) - 1
    while i >= 0:
        dv: int = digits[i]
        result.append(dv)
        i = i - 1
    return result


def count_operators(tokens: list[int]) -> int:
    """Count the number of operator tokens."""
    cnt: int = 0
    i: int = 0
    n: int = len(tokens)
    while i < n:
        tok: int = tokens[i]
        if tok == 43 or tok == 45 or tok == 42:
            cnt = cnt + 1
        i = i + 1
    return cnt


def test_module() -> int:
    """Test expression evaluator functions."""
    passed: int = 0

    d1: int = is_digit_token(50)
    if d1 == 1:
        passed = passed + 1

    d2: int = is_digit_token(43)
    if d2 == 0:
        passed = passed + 1

    tokens1: list[int] = [49, 43, 50]
    r1: int = eval_simple(tokens1)
    if r1 == 3:
        passed = passed + 1

    tokens2: list[int] = [53, 45, 51]
    r2: int = eval_simple(tokens2)
    if r2 == 2:
        passed = passed + 1

    toks: list[int] = tokenize_digits(42)
    if len(toks) == 2:
        passed = passed + 1

    ops: int = count_operators([49, 43, 50, 42, 51])
    if ops == 2:
        passed = passed + 1

    return passed
