# Generated by: depyler corpus generator
# Source: hard_algo_selection_sort.py
#
# Selection sort and min/max finding algorithms.


def selection_sort_asc(arr: List[int]) -> List[int]:
    """Selection sort ascending on a copy."""
    result: List[int] = []
    i: int = 0
    while i < len(arr):
        result.append(arr[i])
        i = i + 1
    n: int = len(result)
    i = 0
    while i < n - 1:
        min_idx: int = i
        j: int = i + 1
        while j < n:
            if result[j] < result[min_idx]:
                min_idx = j
            j = j + 1
        if min_idx != i:
            tmp: int = result[i]
            result[i] = result[min_idx]
            result[min_idx] = tmp
        i = i + 1
    return result


def selection_sort_desc(arr: List[int]) -> List[int]:
    """Selection sort descending on a copy."""
    result: List[int] = []
    i: int = 0
    while i < len(arr):
        result.append(arr[i])
        i = i + 1
    n: int = len(result)
    i = 0
    while i < n - 1:
        max_idx: int = i
        j: int = i + 1
        while j < n:
            if result[j] > result[max_idx]:
                max_idx = j
            j = j + 1
        if max_idx != i:
            tmp: int = result[i]
            result[i] = result[max_idx]
            result[max_idx] = tmp
        i = i + 1
    return result


def find_min_val(arr: List[int]) -> int:
    """Find minimum value in array. Returns -1 for empty."""
    n: int = len(arr)
    if n == 0:
        return -1
    best: int = arr[0]
    i: int = 1
    while i < n:
        if arr[i] < best:
            best = arr[i]
        i = i + 1
    return best


def find_max_val(arr: List[int]) -> int:
    """Find maximum value in array. Returns -1 for empty."""
    n: int = len(arr)
    if n == 0:
        return -1
    best: int = arr[0]
    i: int = 1
    while i < n:
        if arr[i] > best:
            best = arr[i]
        i = i + 1
    return best


def find_kth_smallest(arr: List[int], kth: int) -> int:
    """Find k-th smallest element (0-indexed) using selection."""
    sorted_arr: List[int] = selection_sort_asc(arr)
    n: int = len(sorted_arr)
    if kth < 0 or kth >= n:
        return -1
    return sorted_arr[kth]


def test_module() -> int:
    """Test all selection sort and min/max functions."""
    passed: int = 0

    r1: List[int] = selection_sort_asc([9, 1, 4, 7, 2])
    if r1 == [1, 2, 4, 7, 9]:
        passed = passed + 1

    r2: List[int] = selection_sort_asc([])
    if r2 == []:
        passed = passed + 1

    r3: List[int] = selection_sort_desc([1, 5, 3, 2, 4])
    if r3 == [5, 4, 3, 2, 1]:
        passed = passed + 1

    r4: int = find_min_val([3, 1, 4, 1, 5])
    if r4 == 1:
        passed = passed + 1

    r5: int = find_max_val([3, 1, 4, 1, 5])
    if r5 == 5:
        passed = passed + 1

    r6: int = find_kth_smallest([7, 2, 9, 1, 5], 2)
    if r6 == 5:
        passed = passed + 1

    r7: int = find_min_val([])
    if r7 == -1:
        passed = passed + 1

    return passed
