# Generated by: depyler corpus generator
# Source: hard_cp_ds_skiplist.py
#
# Skip-list-like sorted operations for transpiler stress testing.


def sorted_insert(arr: list[int], val: int) -> list[int]:
    """Insert val into sorted array maintaining order."""
    result: list[int] = []
    inserted: int = 0
    i: int = 0
    while i < len(arr):
        if inserted == 0 and val <= arr[i]:
            result.append(val)
            inserted = 1
        result.append(arr[i])
        i = i + 1
    if inserted == 0:
        result.append(val)
    return result


def sorted_delete(arr: list[int], val: int) -> list[int]:
    """Delete first occurrence of val from sorted array."""
    result: list[int] = []
    removed: int = 0
    i: int = 0
    while i < len(arr):
        if removed == 0 and arr[i] == val:
            removed = 1
        else:
            result.append(arr[i])
        i = i + 1
    return result


def sorted_search(arr: list[int], val: int) -> int:
    """Binary search in sorted array. Returns index or -1."""
    lo: int = 0
    hi: int = len(arr) - 1
    while lo <= hi:
        mid: int = (lo + hi) // 2
        if arr[mid] == val:
            return mid
        elif arr[mid] < val:
            lo = mid + 1
        else:
            hi = mid - 1
    return 0 - 1


def sorted_rank(arr: list[int], val: int) -> int:
    """Count elements strictly less than val."""
    lo: int = 0
    hi: int = len(arr)
    while lo < hi:
        mid: int = (lo + hi) // 2
        if arr[mid] < val:
            lo = mid + 1
        else:
            hi = mid
    return lo


def sorted_kth_smallest(arr: list[int], k: int) -> int:
    """Return k-th smallest element (0-indexed)."""
    if k < 0 or k >= len(arr):
        return 0 - 1
    return arr[k]


def test_module() -> int:
    passed: int = 0
    arr: list[int] = [1, 3, 5, 7, 9]
    result: list[int] = sorted_insert(arr, 4)
    if result == [1, 3, 4, 5, 7, 9]:
        passed = passed + 1
    result2: list[int] = sorted_delete(result, 5)
    if result2 == [1, 3, 4, 7, 9]:
        passed = passed + 1
    if sorted_search([1, 3, 5, 7, 9], 5) == 2:
        passed = passed + 1
    if sorted_rank([1, 3, 5, 7, 9], 6) == 3:
        passed = passed + 1
    if sorted_kth_smallest([1, 3, 5, 7, 9], 2) == 5:
        passed = passed + 1
    return passed
