# Generated by: depyler corpus generator
# Source: hard_adv_hash_probe.py
#
# Hash table with linear and quadratic probing for collision resolution.


def hash_func(val: int, capacity: int) -> int:
    """Simple multiplicative hash function."""
    h: int = ((val * 2654435) % 1000000007) % capacity
    return h


def linear_probe_insert(tbl: list[int], capacity: int, val: int) -> list[int]:
    """Insert value using linear probing. -1 means empty slot."""
    idx: int = hash_func(val, capacity)
    steps: int = 0
    while steps < capacity:
        slot: int = tbl[(idx + steps) % capacity]
        if slot == -1:
            tbl[(idx + steps) % capacity] = val
            return tbl
        steps = steps + 1
    return tbl


def linear_probe_find(tbl: list[int], capacity: int, val: int) -> int:
    """Find value using linear probing. Returns index or -1."""
    idx: int = hash_func(val, capacity)
    steps: int = 0
    while steps < capacity:
        pos: int = (idx + steps) % capacity
        slot: int = tbl[pos]
        if slot == val:
            return pos
        if slot == -1:
            return -1
        steps = steps + 1
    return -1


def quadratic_probe_insert(tbl: list[int], capacity: int, val: int) -> list[int]:
    """Insert value using quadratic probing."""
    idx: int = hash_func(val, capacity)
    step: int = 0
    while step < capacity:
        pos: int = (idx + step * step) % capacity
        slot: int = tbl[pos]
        if slot == -1:
            tbl[pos] = val
            return tbl
        step = step + 1
    return tbl


def count_collisions(tbl: list[int]) -> int:
    """Count non-empty slots (occupied entries)."""
    cnt: int = 0
    i: int = 0
    n: int = len(tbl)
    while i < n:
        slot: int = tbl[i]
        if slot != -1:
            cnt = cnt + 1
        i = i + 1
    return cnt


def make_empty_table(capacity: int) -> list[int]:
    """Create an empty hash table with -1 sentinel values."""
    tbl: list[int] = []
    i: int = 0
    while i < capacity:
        tbl.append(-1)
        i = i + 1
    return tbl


def test_module() -> int:
    """Test hash table probing functions."""
    passed: int = 0

    tbl1: list[int] = make_empty_table(16)
    if len(tbl1) == 16:
        passed = passed + 1

    tbl2: list[int] = make_empty_table(16)
    tbl2 = linear_probe_insert(tbl2, 16, 42)
    found: int = linear_probe_find(tbl2, 16, 42)
    if found >= 0:
        passed = passed + 1

    not_found: int = linear_probe_find(tbl2, 16, 999)
    if not_found == -1:
        passed = passed + 1

    tbl3: list[int] = make_empty_table(16)
    tbl3 = linear_probe_insert(tbl3, 16, 10)
    tbl3 = linear_probe_insert(tbl3, 16, 20)
    tbl3 = linear_probe_insert(tbl3, 16, 30)
    occ: int = count_collisions(tbl3)
    if occ == 3:
        passed = passed + 1

    tbl4: list[int] = make_empty_table(16)
    tbl4 = quadratic_probe_insert(tbl4, 16, 55)
    c4: int = count_collisions(tbl4)
    if c4 == 1:
        passed = passed + 1

    h1: int = hash_func(100, 16)
    if h1 >= 0 and h1 < 16:
        passed = passed + 1

    return passed
