# Generated by: depyler corpus generator
# Source: hard_cp_math_mobius.py
#
# Mobius function and sieve for transpiler stress testing.


def mobius(n: int) -> int:
    """Mobius function: 0 if square factor, (-1)^k for k distinct primes."""
    if n == 1:
        return 1
    prime_factors: int = 0
    temp: int = n
    p: int = 2
    while p * p <= temp:
        if temp % p == 0:
            prime_factors = prime_factors + 1
            temp = temp // p
            if temp % p == 0:
                return 0
        p = p + 1
    if temp > 1:
        prime_factors = prime_factors + 1
    if prime_factors % 2 == 0:
        return 1
    return 0 - 1


def mobius_sieve(limit: int) -> list[int]:
    """Sieve of Mobius function for 1..limit."""
    mu: list[int] = [0] * (limit + 1)
    mu[1] = 1
    is_prime: list[int] = [1] * (limit + 1)
    primes: list[int] = []
    i: int = 2
    while i <= limit:
        if is_prime[i] == 1:
            primes.append(i)
            mu[i] = 0 - 1
        j: int = 0
        while j < len(primes):
            pr: int = primes[j]
            prod: int = i * pr
            if prod > limit:
                j = len(primes)
            else:
                is_prime[prod] = 0
                if i % pr == 0:
                    mu[prod] = 0
                    j = len(primes)
                else:
                    mu[prod] = 0 - mu[i]
            j = j + 1
        i = i + 1
    return mu


def mertens_function(n: int) -> int:
    """Mertens function M(n) = sum of mobius(k) for k=1..n."""
    total: int = 0
    k: int = 1
    while k <= n:
        total = total + mobius(k)
        k = k + 1
    return total


def is_square_free(n: int) -> int:
    """Check if n is square-free. Returns 1=yes, 0=no."""
    p: int = 2
    while p * p <= n:
        if n % (p * p) == 0:
            return 0
        p = p + 1
    return 1


def test_module() -> int:
    passed: int = 0
    if mobius(1) == 1:
        passed = passed + 1
    if mobius(6) == 1:
        passed = passed + 1
    if mobius(4) == 0:
        passed = passed + 1
    sieve: list[int] = mobius_sieve(10)
    if sieve[6] == 1:
        passed = passed + 1
    if mertens_function(10) == 0 - 1:
        passed = passed + 1
    if is_square_free(30) == 1:
        passed = passed + 1
    return passed
