// Generated by: depyler transpile ./examples/simple_array_test.py
// Source: ./examples/simple_array_test.py
// Command: depyler transpile ./examples/simple_array_test.py

#[doc = " Depyler: proven to terminate"] pub fn test_arrays()  -> Result<DynamicType, IndexError>{
    let mut _cse_temp_0 = arr1.get(0 as usize).copied().unwrap_or_default() + arr1.get(1 as usize).copied().unwrap_or_default();
    let mut sum_val = _cse_temp_0;
    return Ok(sum_val)
}