// Generated by: depyler transpile examples/simple_lifetime.py
// Source: examples/simple_lifetime.py
// Command: depyler transpile examples/simple_lifetime.py

#[doc = "Get string length"] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn get_len(s: String)  -> i32 {
    return s.len();
   
}
#[doc = "Return the input unchanged"] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn identity(x: String)  -> String {
    return x
}
