// Generated by: depyler transpile ./examples/test_frozenset.py
// Source: ./examples/test_frozenset.py
// Command: depyler transpile ./examples/test_frozenset.py

#[doc = "Test frozenset functionality"] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn test_frozenset()  -> DynamicType {
    return(fs1, fs2, fs3)
}