// Generated by: depyler transpile ./examples/test_simple_continue.py
// Source: ./examples/test_simple_continue.py
// Command: depyler transpile ./examples/test_simple_continue.py

#[doc = "Test basic continue statement"] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn test_simple_continue()  -> DynamicType {
    for i in 0..5 {
    if i == 2 {
    continue;
   
}
print(i);
   
}
}