// Generated by: depyler transpile ./examples/test_basic_class.py
// Source: ./examples/test_basic_class.py
// Command: depyler transpile ./examples/test_basic_class.py

#[doc = "// TODO: Map Python module 'dataclasses'"] #[derive(Debug, Clone, PartialEq)] pub struct Counter {
    pub value: i32
}
impl Counter {
    pub fn new(value: i32)  -> Self {
    Self {
    value
}
} pub fn increment(& mut self) {
    self.value = self.value + 1;
   
}
pub fn get_value(& mut self)  -> i32 {
    return self.value;
   
}
pub fn create_with_value(val: i32) {
    return Counter::new(val);
   
}
} #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn test_counter()  -> DynamicType {
    let mut c = Counter::new(0);
    c.increment();
    c.increment();
    return(val, c2.value)
}