// Generated by: depyler transpile examples/test_set_basic.py
// Source: examples/test_set_basic.py
// Command: depyler transpile examples/test_set_basic.py

use std::collections::HashSet;
    #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn test_set_creation()  -> serde_json::Value {
    let mut s1 = set();
    let mut s2 = {
    let mut set = HashSet::new();
    set.insert(1);
    set.insert(2);
    set.insert(3);
    set.insert(4);
    set.insert(5);
    set };
    let mut s3 = {
    let mut set = HashSet::new();
    set.insert("apple".to_string());
    set.insert("banana".to_string());
    set.insert("cherry".to_string());
    set };
    let mut s4 = set([1, 2, 3, 3, 4, 4, 5]);
    return s2;
   
}
#[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn test_set_with_duplicates()  -> serde_json::Value {
    let mut s = {
    let mut set = HashSet::new();
    set.insert(1);
    set.insert(2);
    set.insert(2);
    set.insert(3);
    set.insert(3);
    set.insert(3);
    set.insert(4);
    set };
    return s
}
