// Generated by: depyler transpile ./examples/test_nested_access.py
// Source: ./examples/test_nested_access.py
// Command: depyler transpile ./examples/test_nested_access.py

#[doc = "Test reading nested dictionary values"] #[doc = " Depyler: proven to terminate"] pub fn test_nested_access()  -> Result<DynamicType, IndexError>{
    let mut val = d.get("outer".to_string() as usize).copied().unwrap_or_default().get("inner".to_string() as usize).copied().unwrap_or_default();
    return Ok(val)
}