// Generated by: depyler transpile examples/test_simple_set_typed.py
// Source: examples/test_simple_set_typed.py
// Command: depyler transpile examples/test_simple_set_typed.py

use std::collections::HashSet;
    #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn test_simple_set()  -> HashSet<i32>{
    let mut s1 = {
    let mut set = HashSet::new();
    set.insert(1);
    set.insert(2);
    set.insert(3);
    set };
    let mut s2 = {
    let mut set = HashSet::new();
    set.insert(3);
    set.insert(4);
    set.insert(5);
    set };
    let mut result = s1.union(& s2).cloned().collect();
    return result;
   
}
#[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn test_set_method()  -> HashSet<String>{
    let mut fruits = {
    let mut set = HashSet::new();
    set.insert("apple".to_string());
    set.insert("banana".to_string());
    set };
    fruits.insert("cherry".to_string());
    return fruits
}
