// Generated by: depyler transpile examples/v1_2_0_basic_oop.py
// Source: examples/v1_2_0_basic_oop.py
// Command: depyler transpile examples/v1_2_0_basic_oop.py

#[derive(Debug, Clone)] pub struct Point {
    pub x: i32, pub y: i32
}
impl Point {
    pub fn new(x: i32, y: i32)  -> Self {
    Self {
    x, y
}
} pub fn translate(& mut self, dx: i32, dy: i32) {
    self.x = self.x + dx;
    self.y = self.y + dy;
   
}
pub fn distance_squared(& mut self)  -> i32 {
    return self.x * self.x + self.y * self.y;
   
}
pub fn origin ()  -> i32 {
    return 0;
   
}
} #[derive(Debug, Clone)] pub struct Rectangle {
    pub width: i32, pub height: i32
}
impl Rectangle {
    pub fn new(width: i32, height: i32)  -> Self {
    Self {
    width, height
}
} pub fn area(& mut self)  -> i32 {
    return self.width * self.height;
   
}
pub fn perimeter(& mut self)  -> i32 {
    return 2 * self.width + self.height;
   
}
pub fn is_square(& mut self)  -> bool {
    return self.width == self.height;
   
}
} #[doc = "Test Point class"] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn test_point()  -> DynamicType {
    let mut p = Point::new(3, 4);
    p.translate(1, 2);
    let mut dist_sq = p.distance_squared();
    return dist_sq;
   
}
#[doc = "Test Rectangle class"] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn test_rectangle()  -> DynamicType {
    let mut rect = Rectangle::new(10, 20);
    let mut area = rect.area();
    let mut perim = rect.perimeter();
    let mut square = rect.is_square();
    let mut sq = Rectangle::new(5, 5);
    let mut is_sq = sq.is_square();
    return(area + perim);
   
}
#[doc = "Test static methods"] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn test_static()  -> DynamicType {
    let mut zero = Point.origin ();
    return zero;
   
}
#[doc = "Run all tests"] #[doc = " Depyler: verified panic-free"] #[doc = " Depyler: proven to terminate"] pub fn main ()  -> DynamicType {
    let mut point_result = test_point();
    let mut rect_result = test_rectangle();
    let mut static_result = test_static();
    return((point_result + rect_result) + static_result)
}
