// Generated by: DEPYLER stdlib validation Phase 1
// Module: json - Basic JSON serialization/deserialization
// Status: GREEN phase - Tests enabled

use depyler_core::transpile_python_to_rust;

// Note: dumps() and loads() were already implemented
// This commit adds indent parameter support to dumps()

// DEPYLER-STDLIB-JSON-BASICS-001: Serialize to JSON
#[test]
fn test_json_dumps() {
    let python = r#"
import json

def to_json(data: dict) -> str:
    return json.dumps(data)
"#;

    let result = transpile_python_to_rust(python).expect("Transpilation failed");

    // Should serialize to JSON string
    assert!(result.contains("to_string"));
}

// DEPYLER-STDLIB-JSON-BASICS-002: Deserialize from JSON
#[test]
fn test_json_loads() {
    let python = r#"
import json

def from_json(text: str) -> dict:
    return json.loads(text)
"#;

    let result = transpile_python_to_rust(python).expect("Transpilation failed");

    // Should deserialize from JSON string
    assert!(result.contains("from_str"));
}

// DEPYLER-STDLIB-JSON-BASICS-003: Pretty print JSON
#[test]
fn test_json_dumps_pretty() {
    let python = r#"
import json

def to_pretty_json(data: dict) -> str:
    return json.dumps(data, indent=2)
"#;

    let result = transpile_python_to_rust(python).expect("Transpilation failed");

    // Should serialize with pretty printing
    assert!(result.contains("to_string_pretty"));
}

// Total: 1 NEW function (dumps with indent), 2 already existed
// Coverage: dumps(), loads(), dumps(indent=)
