// Generated by: DEPYLER stdlib validation Phase 1
// Module: shlex - Python shlex module validation
// Status: RED phase - Tests written first, implementation pending

use depyler_core::transpile_python_to_rust;

// DEPYLER-STDLIB-SHLEX-001: Shell splitting
#[test]
fn test_split() {
    let python = r#"
import shlex

def split_shell(s: str) -> list:
    return shlex.split(s)
"#;

    let result = transpile_python_to_rust(python).expect("Transpilation failed");

    // Should split string like shell does (respects quotes)
    assert!(result.contains("in_single_quote") || result.contains("in_double_quote"));
    assert!(result.contains("escaped"));
}

// DEPYLER-STDLIB-SHLEX-002: Shell quoting
#[test]
fn test_quote() {
    let python = r#"
import shlex

def quote_shell(s: str) -> str:
    return shlex.quote(s)
"#;

    let result = transpile_python_to_rust(python).expect("Transpilation failed");

    // Should quote string for safe shell usage
    assert!(result.contains("needs_quoting"));
    assert!(result.contains("format"));
}

// DEPYLER-STDLIB-SHLEX-003: Shell joining
#[test]
fn test_join() {
    let python = r#"
import shlex

def join_shell(args: list) -> str:
    return shlex.join(args)
"#;

    let result = transpile_python_to_rust(python).expect("Transpilation failed");

    // Should join list with proper shell escaping
    assert!(result.contains("needs_quoting"));
    assert!(result.contains("join"));
}

// Total: 3 comprehensive tests for shlex module
// Coverage: split, quote, join
// Security: Proper shell escaping to prevent injection
