// Generated by: DEPYLER stdlib validation Phase 1
// Module: time - Basic time functions
// Status: GREEN phase - Tests enabled

use depyler_core::transpile_python_to_rust;

// Note: All 3 time functions were already implemented
// This commit verifies existing implementations

// DEPYLER-STDLIB-TIME-BASICS-001: Current time (already implemented)
#[test]
fn test_time() {
    let python = r#"
import time

def current_time() -> float:
    return time.time()
"#;

    let result = transpile_python_to_rust(python).expect("Transpilation failed");

    // Should get current Unix timestamp
    assert!(result.contains("SystemTime::now") && result.contains("as_secs_f64"));
}

// DEPYLER-STDLIB-TIME-BASICS-002: Sleep (already implemented)
#[test]
fn test_sleep() {
    let python = r#"
import time

def wait(seconds: float) -> None:
    time.sleep(seconds)
"#;

    let result = transpile_python_to_rust(python).expect("Transpilation failed");

    // Should sleep for specified seconds
    assert!(result.contains("thread::sleep") && result.contains("Duration"));
}

// DEPYLER-STDLIB-TIME-BASICS-003: Monotonic time (already implemented)
#[test]
fn test_monotonic() {
    let python = r#"
import time

def monotonic_time() -> float:
    return time.monotonic()
"#;

    let result = transpile_python_to_rust(python).expect("Transpilation failed");

    // Should get monotonic time
    assert!(result.contains("Instant::now"));
}

// Total: 3 time functions verified (all already existed)
// Coverage: time(), sleep(), monotonic()
