// Generated by: DEPYLER stdlib validation Phase 1
// Module: os.path - Additional path functions
// Status: GREEN phase - Tests enabled

use depyler_core::transpile_python_to_rust;

// Note: splitext, dirname, basename, normpath were already implemented
// This commit adds 1 NEW function: relpath

// DEPYLER-STDLIB-OSPATH-ADDITIONAL-001: Get relative path
#[test]
fn test_relpath() {
    let python = r#"
import os.path

def relative_path(path: str, start: str) -> str:
    return os.path.relpath(path, start)
"#;

    let result = transpile_python_to_rust(python).expect("Transpilation failed");

    // Should compute relative path
    assert!(result.contains("strip_prefix") || result.contains("relative"));
}

// Total: 1 NEW os.path function (splitext, dirname, basename, normpath already existed)
// Coverage: relpath()
