name: Publish to MCP Registry

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  publish-to-crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --workspace --all-features

      - name: Publish to crates.io
        run: |
          cargo publish -p depyler-core --token ${{ secrets.CARGO_TOKEN }}
          sleep 30
          cargo publish -p depyler-analyzer --token ${{ secrets.CARGO_TOKEN }}
          sleep 30
          cargo publish -p depyler-verify --token ${{ secrets.CARGO_TOKEN }}
          sleep 30
          cargo publish -p depyler-mcp --token ${{ secrets.CARGO_TOKEN }}
          sleep 30
          cargo publish -p depyler-annotations --token ${{ secrets.CARGO_TOKEN }}
          sleep 30
          cargo publish -p depyler-quality --token ${{ secrets.CARGO_TOKEN }}
          sleep 30
          cargo publish -p depyler-ruchy --token ${{ secrets.CARGO_TOKEN }}
          sleep 30
          cargo publish -p depyler-wasm --token ${{ secrets.CARGO_TOKEN }}
          sleep 30
          cargo publish -p depyler --token ${{ secrets.CARGO_TOKEN }}

  publish-to-mcp-registry:
    name: Publish to MCP Registry
    needs: publish-to-crates
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for crates.io availability
        run: |
          echo "Waiting 60 seconds for crates.io to index the package..."
          sleep 60

      - name: Install MCP Publisher
        run: |
          curl -L "https://github.com/modelcontextprotocol/registry/releases/download/v1.2.3/mcp-publisher_1.2.3_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').tar.gz" | tar xz

      - name: Login to MCP Registry
        run: ./mcp-publisher login github-oidc

      - name: Publish to MCP Registry
        run: ./mcp-publisher publish

      - name: Verify publication
        run: |
          sleep 10
          curl "https://registry.modelcontextprotocol.io/v0/servers?search=depyler" | jq .
